title: Rezeptdatenbank
theme: minima
url: "https://fraokis.github.io"
baseurl: "/frasrezepte.github.io"


collections:
  recipes:
    output: true
    permalink: /rezepte/:name/

defaults:
  - scope:
      path: ""
      type: recipes
    values:
      layout: recipe
